[versions]

# app
app_compileSdk = "33"
app_minSdk = "16"
app_minSdk_compose = "21"
app_targetSdk = "32"
app_versionCode = "1"
app_versionName = "1.0"

# kotlin
kotlin = "1.7.10"
kotlinx_coroutines = "1.6.4"
kotlinx_serialization_json = "1.3.3"

# android
android_plugin = "7.3.0"
androidx_activity = "1.6.0"
androidx_annotation = "1.5.0"
androidx_appcompat = "1.5.1"
androidx_compose = "1.2.1"
androidx_compose_compiler = "1.3.1"
androidx_compose_material3 = "1.0.0-beta03"
androidx_constraintlayout = "2.1.4"
androidx_constraintlayout_compose = "1.0.1"
androidx_core = "1.9.0"
androidx_fragment = "1.5.3"
androidx_lifecycle = "2.5.1"
androidx_multidex = "2.0.1"
androidx_navigation = "2.5.2"
androidx_paging = "3.1.1"
androidx_paging_compose = "1.0.0-alpha16"
androidx_recyclerview = "1.2.1"
androidx_swiperefreshlayout = "1.1.0"

# google
google_material = "1.6.1"
google_accompanist = "0.25.0"

# other
assemblyadapter4 = "4.1.0"
tools4a = "1.0.0"
tools4j = "1.0.0"
tools4k = "1.0.0"
sketch3 = "3.1.0-rc01"
retrofit2 = "2.6.4"
retrofit2_kotlinxSerializationConverter = "0.8.0"
okhttp3 = "3.12.0"   # 3.12.9 是最后一个支持 Android 5.0 以下的版本
leakcanary = "2.9.1"

[libraries]

# kotlin
kotlin_plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin_stdlib_jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin_serialization_plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlinx_coroutines_android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx_coroutines" }
kotlinx_serialization_json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx_serialization.json" }

# android
android_plugin = { module = "com.android.tools.build:gradle", version.ref = "android_plugin" }
androidx_activity = { module = "androidx.activity:activity", version.ref = "androidx_activity" }
androidx_activity_compose = { module = "androidx.activity:activity-compose", version.ref = "androidx_activity" }
androidx_annotation = { module = "androidx.annotation:annotation", version.ref = "androidx_annotation" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx_appcompat" }
androidx_compose_foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx_compose" }
androidx_compose_material = { module = "androidx.compose.material:material", version.ref = "androidx_compose" }
androidx_compose_animation = { module = "androidx.compose.animation:animation", version.ref = "androidx_compose" }
androidx_compose_ui_tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx_compose" }
androidx_compose_ui_test_manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx_compose" }
androidx_compose_material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx_compose_material3" }
androidx_constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx_constraintlayout" }
androidx_constraintlayout_compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx_constraintlayout_compose" }
androidx_core = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
androidx_fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx_fragment" }
androidx_lifecycle_runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx_lifecycle" }
androidx_lifecycle_viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx_lifecycle" }
androidx_lifecycle_viewmodel_compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx_lifecycle" }
androidx_multidex = { module = "androidx.multidex:multidex", version.ref = "androidx_multidex" }
androidx_navigation_fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx_navigation" }
androidx_navigation_ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx_navigation" }
androidx_navigation_compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx_navigation" }
androidx_navigation_safeargsgradle_plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx_navigation" }
androidx_paging_common = { module = "androidx.paging:paging-common", version.ref = "androidx_paging" }
androidx_paging_runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx_paging" }
androidx_paging_compose = { module = "androidx.paging:paging-compose", version.ref = "androidx_paging_compose" }
androidx_recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx_recyclerview" }
androidx_swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx_swiperefreshlayout" }

# google
google_material = { module = "com.google.android.material:material", version.ref = "google_material" }

# other
assemblyadapter4 = { module = "io.github.panpf.assemblyadapter4:assemblyadapter", version.ref = "assemblyadapter4" }
sketch3 = { module = "io.github.panpf.sketch3:sketch", version.ref = "sketch3" }
tools4j = { module = "io.github.panpf.tools4j:tools4j-ktx", version.ref = "tools4j" }
tools4a = { module = "io.github.panpf.tools4a:tools4a-ktx", version.ref = "tools4a" }
tools4k = { module = "io.github.panpf.tools4k:tools4k", version.ref = "tools4k" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit2_kotlinxSerializationConverter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2_kotlinxSerializationConverter" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp3_logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

[bundles]
androidx_lifecycle = [
    "androidx_lifecycle_runtime",
    "androidx_lifecycle_viewmodel",
]
androidx_lifecycle_compose = [
    "androidx_lifecycle_runtime",
    "androidx_lifecycle_viewmodel",
    "androidx_lifecycle_viewmodel_compose",
]
androidx_compose = [
    "androidx_compose_foundation",
    "androidx_compose_material",
    "androidx_compose_animation",
    "androidx_compose_material3",
]
androidx_compose_debug = [
    "androidx_compose_ui_tooling",
    "androidx_compose_ui_test_manifest",
]
androidx_navigation = [
    "androidx_navigation_fragment",
    "androidx_navigation_ui",
]
androidx_navigation_compose = [
    "androidx_navigation_fragment",
    "androidx_navigation_ui",
    "androidx_navigation_compose",
]